'use strict';

const fs = require('fs');
const path = require('path');
const BaseCommand = require('../../core/BaseCommand');
const config = require('../../config');
const registry = require('../../registry');
const wirer = require('../../wirer');

const POINTER_RE = /^<!-- Managed by easyskillz -->\s*<!-- See: .*? -->\s*$/s;

class DoctorCommand extends BaseCommand {
  constructor(options) {
    super(options);
  }

  async execute() {
    const issues = [];
    const cfg = config.read(this.cwd);

    this.checkStaleTargets(issues);
    this.checkInstructionFiles(issues);
    this.checkSkillMetadata(issues);
    this.checkRegisteredTargets(cfg, issues);

    if (this.json) {
      this.jsonOutput({
        ok: issues.length === 0,
        issueCount: issues.length,
        issues,
      });
      return;
    }

    if (issues.length === 0) {
      this.out('No easyskillz compatibility issues found.');
      return;
    }

    this.out(`Found ${issues.length} compatibility issue(s):`);
    for (const issue of issues) {
      this.out(`  [${issue.code}] ${issue.path}`);
      this.out(`    ${issue.message}`);
    }
  }

  checkStaleTargets(issues) {
    for (const stalePath of ['.codex/skills', '.cursor/skills']) {
      const absolute = path.join(this.cwd, stalePath);
      if (fs.existsSync(absolute)) {
        issues.push({
          code: 'stale-target',
          path: stalePath,
          message: 'This legacy target is no longer emitted by easyskillz 0.3.0.',
        });
      }
    }
  }

  checkInstructionFiles(issues) {
    const candidates = ['AGENTS.md', 'CLAUDE.md', 'GEMINI.md', '.github/copilot-instructions.md'];
    for (const relPath of candidates) {
      const absolute = path.join(this.cwd, relPath);
      if (!fs.existsSync(absolute)) continue;

      const content = fs.readFileSync(absolute, 'utf8').trim();
      if (POINTER_RE.test(content)) {
        issues.push({
          code: 'pointer-instruction',
          path: relPath,
          message: 'Instruction file only points elsewhere; agents need real instruction content here.',
        });
      }
    }
  }

  checkSkillMetadata(issues) {
    const skillsDir = path.join(this.cwd, '.easyskillz', 'skills');
    if (!fs.existsSync(skillsDir)) return;

    for (const name of fs.readdirSync(skillsDir)) {
      const skillPath = path.join(skillsDir, name);
      if (!fs.statSync(skillPath).isDirectory()) continue;

      const parsed = wirer.parseSkillFile(skillPath, name);
      const description = parsed.frontmatter.description || '';
      if (!parsed.frontmatter.name || !description || description === 'autogenerated so ai agents can see the skill') {
        issues.push({
          code: 'weak-skill-metadata',
          path: path.join('.easyskillz', 'skills', name, 'SKILL.md'),
          message: 'Skill frontmatter needs a name and a meaningful description for model activation.',
        });
      }
    }
  }

  checkRegisteredTargets(cfg, issues) {
    const skillsDir = path.join(this.cwd, '.easyskillz', 'skills');
    if (!fs.existsSync(skillsDir)) return;

    const skills = fs.readdirSync(skillsDir).filter((name) =>
      fs.statSync(path.join(skillsDir, name)).isDirectory()
    );

    for (const toolId of cfg.tools || []) {
      const entry = registry[toolId];
      if (!entry) continue;
      for (const skill of skills) {
        const srcPath = path.join(skillsDir, skill);
        for (const target of wirer.getSkillTargets(entry, skill, srcPath)) {
          if (!fs.existsSync(path.join(this.cwd, target.targetPath))) {
            issues.push({
              code: 'missing-target',
              path: target.targetPath,
              message: `Registered tool "${toolId}" is missing generated output for skill "${skill}".`,
            });
          }
        }
      }
    }
  }
}

module.exports = DoctorCommand;
