'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

// Test whether symlinks can be created in this environment.
// Uses a temp dir so we never pollute the project.
function probeSymlinks() {
  const src = path.join(os.tmpdir(), `easyskillz-probe-src-${Date.now()}`);
  const dst = path.join(os.tmpdir(), `easyskillz-probe-dst-${Date.now()}`);
  try {
    fs.mkdirSync(src);
    const type = process.platform === 'win32' ? 'junction' : undefined;
    fs.symlinkSync(src, dst, type);
    const resolved = fs.realpathSync(dst);
    return resolved.toLowerCase() === src.toLowerCase();
  } catch {
    return false;
  } finally {
    try { fs.rmSync(src, { recursive: true, force: true }); } catch {}
    try { fs.rmSync(dst, { recursive: true, force: true }); } catch {}
  }
}

// Check whether a path is already correctly wired (symlink to right src, or stub file present).
function isWired(targetDir, skillName, srcPath, strategy, toolEntry) {
  const isWorkflow = toolEntry && toolEntry.type === 'workflows';
  const target = isWorkflow
    ? path.join(targetDir, skillName + '.md')
    : path.join(targetDir, skillName);

  if (!fs.existsSync(target)) return false;

  if (strategy === 'symlink') {
    try {
      const stat = fs.lstatSync(target);
      if (!stat.isSymbolicLink()) return false;
      const resolved = fs.realpathSync(target);
      const expectedSrc = isWorkflow
        ? path.join(srcPath, 'SKILL.md')
        : srcPath;
      return resolved.toLowerCase() === expectedSrc.toLowerCase();
    } catch {
      return false;
    }
  }
  // stub
  const stubFile = isWorkflow ? target : path.join(target, 'SKILL.md');
  if (!fs.existsSync(stubFile)) return false;
  const content = fs.readFileSync(stubFile, 'utf8');
  return content.includes('easyskillz') && content.includes(skillName);
}

// Ensure a skill has valid Gemini CLI frontmatter.
// Repaired in-place if missing.
function ensureValidSkill(skillPath, skillName) {
  const skillMd = path.join(skillPath, 'SKILL.md');
  if (!fs.existsSync(skillMd)) return;

  const content = fs.readFileSync(skillMd, 'utf8');
  if (content.trim().startsWith('---')) return;

  const frontmatter = [
    '---',
    `name: ${skillName}`,
    'description: autogenerated so ai agents can see the skill',
    '---',
    '',
  ].join('\n');

  fs.writeFileSync(skillMd, frontmatter + content, 'utf8');
}

// Wire a single skill into a tool's skills directory.
// For workflow-type tools, wires SKILL.md as a flat .md file (skill-name.md).
// Returns 'wired' | 'already'
function wireSkill(skillName, toolEntry, cwd, strategy) {
  const srcPath = path.resolve(cwd, '.easyskillz', 'skills', skillName);

  // Auto-repair source skill format if needed
  ensureValidSkill(srcPath, skillName);

  const toolSkillsDir = path.resolve(cwd, toolEntry.skillsDir);
  const isWorkflow = toolEntry.type === 'workflows';
  const target = isWorkflow
    ? path.join(toolSkillsDir, skillName + '.md')
    : path.join(toolSkillsDir, skillName);

  if (isWired(toolSkillsDir, skillName, srcPath, strategy, toolEntry)) return 'already';

  fs.mkdirSync(toolSkillsDir, { recursive: true });

  try {
    const lstat = fs.lstatSync(target);
    if (lstat.isSymbolicLink() || lstat.isDirectory() || lstat.isFile()) {
      fs.rmSync(target, { recursive: true, force: true });
    }
  } catch {
    // target doesn't exist — nothing to remove
  }

  if (isWorkflow) {
    // Workflows are flat .md files — symlink SKILL.md directly or write stub
    const skillMd = path.join(srcPath, 'SKILL.md');
    if (strategy === 'symlink') {
      try {
        fs.symlinkSync(skillMd, target);
      } catch {
        fs.writeFileSync(target, stubContent(skillName), 'utf8');
      }
    } else {
      fs.writeFileSync(target, stubContent(skillName), 'utf8');
    }
  } else if (strategy === 'symlink') {
    try {
      const type = process.platform === 'win32' ? 'junction' : undefined;
      fs.symlinkSync(srcPath, target, type);
    } catch {
      // symlink failed despite probe passing — fall back to stub
      fs.mkdirSync(target, { recursive: true });
      fs.writeFileSync(path.join(target, 'SKILL.md'), stubContent(skillName), 'utf8');
    }
  } else {
    fs.mkdirSync(target, { recursive: true });
    fs.writeFileSync(path.join(target, 'SKILL.md'), stubContent(skillName), 'utf8');
  }
  return 'wired';
}

function stubContent(skillName) {
  const relPath = path.join('.easyskillz', 'skills', skillName, 'SKILL.md');
  return [
    `# ${skillName}`,
    '',
    '> **Managed by easyskillz** — symlinks are not available in this environment.',
    `> Read the actual skill from: \`${relPath}\``,
    '',
    `The source skill lives at \`.easyskillz/skills/${skillName}/\`.`,
    'Run `easyskillz sync` to re-wire after cloning.',
  ].join('\n') + '\n';
}

// Wire a skill to all locations for a tool (primary + additional wiring).
// Returns array of results: [{ location: string, result: 'wired'|'already' }, ...]
function wireSkillToAllLocations(skillName, toolEntry, cwd, strategy) {
  const results = [];
  
  // Wire to primary location
  results.push({
    location: toolEntry.skillsDir,
    result: wireSkill(skillName, toolEntry, cwd, strategy),
  });
  
  // Wire to additional locations (e.g., Windsurf workflows)
  if (toolEntry.additionalWiring) {
    for (const additionalEntry of toolEntry.additionalWiring) {
      const combinedEntry = { ...toolEntry, ...additionalEntry };
      results.push({
        location: additionalEntry.skillsDir,
        result: wireSkill(skillName, combinedEntry, cwd, strategy),
      });
    }
  }
  
  return results;
}

// Wire all skills in .easyskillz/skills/ to a single tool.
function wireAllSkills(toolEntry, cwd, strategy) {
  const skillsDir = path.join(cwd, '.easyskillz', 'skills');
  if (!fs.existsSync(skillsDir)) return [];
  const skills = fs.readdirSync(skillsDir).filter((n) =>
    fs.statSync(path.join(skillsDir, n)).isDirectory()
  );
  return skills.map((name) => ({
    skill: name,
    results: wireSkillToAllLocations(name, toolEntry, cwd, strategy),
  }));
}

const { writeInstruction: appendInstruction } = require('./docs/syncFolder');
const { updateGitignore } = require('./gitignore/updateGitignore');

// Scan for skills missing from any registered tool's skills dir.
function scanUnwired(cwd, config, registry) {
  const skillsDir = path.join(cwd, '.easyskillz', 'skills');
  if (!fs.existsSync(skillsDir)) return [];
  const skills = fs.readdirSync(skillsDir).filter((n) =>
    fs.statSync(path.join(skillsDir, n)).isDirectory()
  );
  const missing = [];
  for (const skill of skills) {
    for (const toolId of config.tools) {
      const entry = registry[toolId.toLowerCase()];
      if (!entry) continue;
      
      const srcPath = path.resolve(cwd, '.easyskillz', 'skills', skill);
      
      // Check primary location
      if (!isWired(path.resolve(cwd, entry.skillsDir), skill, srcPath, config.linkStrategy, entry)) {
        missing.push({ skill, toolId, entry });
        continue;
      }
      
      // Check additional locations
      if (entry.additionalWiring) {
        let anyAdditionalMissing = false;
        for (const additional of entry.additionalWiring) {
          const combined = { ...entry, ...additional };
          if (!isWired(path.resolve(cwd, combined.skillsDir), skill, srcPath, config.linkStrategy, combined)) {
            anyAdditionalMissing = true;
            break;
          }
        }
        if (anyAdditionalMissing) {
          missing.push({ skill, toolId, entry });
        }
      }
    }
  }
  return missing;
}

module.exports = {
  probeSymlinks,
  wireSkill,
  wireSkillToAllLocations,
  wireAllSkills,
  scanUnwired,
  isWired,
  appendInstruction,
  updateGitignore,
};
