'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

const GENERATED_MARKER = '<!-- easyskillz-generated -->';
const WEAK_DESCRIPTIONS = new Set([
  'autogenerated so ai agents can see the skill',
]);

// Test whether symlinks can be created in this environment.
// Uses a temp dir so we never pollute the project.
function probeSymlinks() {
  const src = path.join(os.tmpdir(), `easyskillz-probe-src-${Date.now()}`);
  const dst = path.join(os.tmpdir(), `easyskillz-probe-dst-${Date.now()}`);
  try {
    fs.mkdirSync(src);
    const type = process.platform === 'win32' ? 'junction' : undefined;
    fs.symlinkSync(src, dst, type);
    const resolved = fs.realpathSync(dst);
    return resolved.toLowerCase() === src.toLowerCase();
  } catch {
    return false;
  } finally {
    try { fs.rmSync(src, { recursive: true, force: true }); } catch {}
    try { fs.rmSync(dst, { recursive: true, force: true }); } catch {}
  }
}

function parseSkillFile(skillPath, skillName) {
  const skillMd = path.join(skillPath, 'SKILL.md');
  const fallback = {
    frontmatter: {},
    body: '',
    rawFrontmatter: [],
    hasFrontmatter: false,
    isWorkflow: false,
  };
  if (!fs.existsSync(skillMd)) return fallback;

  const content = fs.readFileSync(skillMd, 'utf8');
  const lines = content.split(/\r?\n/);
  if (lines[0] !== '---') return { ...fallback, body: content };

  const endIndex = lines.findIndex((line, index) => index > 0 && line === '---');
  if (endIndex === -1) return { ...fallback, body: content };

  const rawFrontmatter = lines.slice(1, endIndex);
  const frontmatter = {};
  for (const line of rawFrontmatter) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (match) frontmatter[match[1]] = match[2].trim().replace(/^["']|["']$/g, '');
  }

  const type = (frontmatter.type || frontmatter.kind || '').toLowerCase();
  const workflow = String(frontmatter.workflow || '').toLowerCase();

  return {
    frontmatter,
    rawFrontmatter,
    body: lines.slice(endIndex + 1).join('\n'),
    hasFrontmatter: true,
    isWorkflow: type === 'workflow' || workflow === 'true' || workflow === 'yes',
  };
}

function meaningfulDescription(skillName) {
  return `Use this skill when asked to run the ${skillName} procedure or follow its project-specific instructions.`;
}

function serializeSkill(rawFrontmatter, frontmatter, body) {
  const lines = [...rawFrontmatter];
  const setField = (key, value) => {
    const index = lines.findIndex((line) => line.match(new RegExp(`^${key}:\\s*`)));
    const next = `${key}: ${value}`;
    if (index === -1) lines.push(next);
    else lines[index] = next;
  };

  setField('name', frontmatter.name);
  setField('description', frontmatter.description);

  return ['---', ...lines, '---', body.replace(/^\n+/, '')].join('\n');
}

// Ensure a skill has portable frontmatter with a useful activation description.
// Repaired in-place if missing or clearly autogenerated.
function ensureValidSkill(skillPath, skillName) {
  const skillMd = path.join(skillPath, 'SKILL.md');
  if (!fs.existsSync(skillMd)) return;

  const parsed = parseSkillFile(skillPath, skillName);
  const frontmatter = { ...parsed.frontmatter };
  let changed = false;

  if (!frontmatter.name) {
    frontmatter.name = skillName;
    changed = true;
  }

  if (!frontmatter.description || WEAK_DESCRIPTIONS.has(frontmatter.description.toLowerCase())) {
    frontmatter.description = meaningfulDescription(skillName);
    changed = true;
  }

  if (!parsed.hasFrontmatter || changed) {
    fs.writeFileSync(
      skillMd,
      serializeSkill(parsed.rawFrontmatter, frontmatter, parsed.body),
      'utf8'
    );
  }
}

function getSkillTargets(toolEntry, skillName, srcPath) {
  const parsed = parseSkillFile(srcPath, skillName);
  const configured = toolEntry.skillTargets || [{ kind: 'skill-dir', path: toolEntry.skillsDir }];
  return configured
    .filter((target) => target.when !== 'workflow' || parsed.isWorkflow)
    .map((target) => {
      const extension =
        target.kind === 'cursor-rule' ? '.mdc' :
        target.kind === 'windsurf-workflow' ? '.md' :
        '';
      const targetName = extension ? `${skillName}${extension}` : skillName;
      return {
        ...target,
        baseDir: target.path,
        targetPath: path.join(target.path, targetName),
        parsed,
      };
    });
}

function renderCursorRule(skillName, parsed) {
  const description = parsed.frontmatter.description || meaningfulDescription(skillName);
  const title = parsed.frontmatter.name || skillName;
  return [
    '---',
    `description: ${description}`,
    'alwaysApply: false',
    '---',
    GENERATED_MARKER,
    `# ${title}`,
    '',
    parsed.body.trim(),
    '',
  ].join('\n');
}

function renderWindsurfWorkflow(skillName, parsed) {
  const title = parsed.frontmatter.name || skillName;
  const description = parsed.frontmatter.description || meaningfulDescription(skillName);
  return [
    GENERATED_MARKER,
    `# ${title}`,
    '',
    description,
    '',
    parsed.body.trim(),
    '',
  ].join('\n');
}

function isTargetWired(cwd, target, srcPath, strategy) {
  const absoluteTarget = path.resolve(cwd, target.targetPath);
  if (!fs.existsSync(absoluteTarget)) return false;

  if (target.kind === 'cursor-rule' || target.kind === 'windsurf-workflow') {
    const content = fs.readFileSync(absoluteTarget, 'utf8');
    const expected = target.kind === 'cursor-rule'
      ? renderCursorRule(path.basename(target.targetPath, '.mdc'), target.parsed)
      : renderWindsurfWorkflow(path.basename(target.targetPath, '.md'), target.parsed);
    return content === expected;
  }

  if (strategy === 'symlink') {
    try {
      const stat = fs.lstatSync(absoluteTarget);
      if (!stat.isSymbolicLink()) return false;
      return fs.realpathSync(absoluteTarget).toLowerCase() === srcPath.toLowerCase();
    } catch {
      return false;
    }
  }

  const sourceSkill = path.join(srcPath, 'SKILL.md');
  const targetSkill = path.join(absoluteTarget, 'SKILL.md');
  if (!fs.existsSync(targetSkill)) return false;
  if (!fs.existsSync(sourceSkill)) return true;
  return fs.readFileSync(sourceSkill, 'utf8') === fs.readFileSync(targetSkill, 'utf8');
}

// Backward-compatible helper used by older tests/callers.
function isWired(targetDir, skillName, srcPath, strategy, toolEntry) {
  if (toolEntry) {
    return getSkillTargets(toolEntry, skillName, srcPath)
      .every((target) => isTargetWired(path.dirname(path.resolve(targetDir)), target, srcPath, strategy));
  }

  const target = path.join(targetDir, skillName);
  if (!fs.existsSync(target)) return false;
  if (strategy === 'symlink') {
    try {
      return fs.realpathSync(target).toLowerCase() === srcPath.toLowerCase();
    } catch {
      return false;
    }
  }
  return fs.existsSync(path.join(target, 'SKILL.md'));
}

function copySkillDirectory(srcPath, targetPath) {
  fs.rmSync(targetPath, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.cpSync(srcPath, targetPath, { recursive: true });
}

// Wire a single skill into all configured targets for a tool.
// Returns 'wired' | 'already'
function wireSkill(skillName, toolEntry, cwd, strategy, skipAutoRepair = false) {
  const srcPath = path.resolve(cwd, '.easyskillz', 'skills', skillName);

  if (!skipAutoRepair) ensureValidSkill(srcPath, skillName);

  const targets = getSkillTargets(toolEntry, skillName, srcPath);
  let changed = false;

  for (const target of targets) {
    const absoluteBase = path.resolve(cwd, target.baseDir);
    const absoluteTarget = path.resolve(cwd, target.targetPath);
    if (isTargetWired(cwd, target, srcPath, strategy)) continue;

    fs.mkdirSync(absoluteBase, { recursive: true });
    fs.rmSync(absoluteTarget, { recursive: true, force: true });

    if (target.kind === 'cursor-rule') {
      fs.writeFileSync(absoluteTarget, renderCursorRule(skillName, target.parsed), 'utf8');
      changed = true;
      continue;
    }

    if (target.kind === 'windsurf-workflow') {
      fs.writeFileSync(absoluteTarget, renderWindsurfWorkflow(skillName, target.parsed), 'utf8');
      changed = true;
      continue;
    }

    if (strategy === 'symlink') {
      try {
        const type = process.platform === 'win32' ? 'junction' : undefined;
        fs.symlinkSync(srcPath, absoluteTarget, type);
      } catch {
        copySkillDirectory(srcPath, absoluteTarget);
      }
    } else {
      copySkillDirectory(srcPath, absoluteTarget);
    }
    changed = true;
  }

  return changed ? 'wired' : 'already';
}

function wireSkillToAllLocations(skillName, toolEntry, cwd, strategy, skipAutoRepair = false) {
  const result = wireSkill(skillName, toolEntry, cwd, strategy, skipAutoRepair);
  const srcPath = path.resolve(cwd, '.easyskillz', 'skills', skillName);
  return getSkillTargets(toolEntry, skillName, srcPath).map((target) => ({
    location: target.targetPath,
    result,
  }));
}

// Wire all skills in .easyskillz/skills/ to a single tool.
function wireAllSkills(toolEntry, cwd, strategy, skipAutoRepair = false) {
  const skillsDir = path.join(cwd, '.easyskillz', 'skills');
  if (!fs.existsSync(skillsDir)) return [];
  const skills = fs.readdirSync(skillsDir).filter((n) =>
    fs.statSync(path.join(skillsDir, n)).isDirectory()
  );
  return skills.map((name) => ({
    skill: name,
    results: wireSkillToAllLocations(name, toolEntry, cwd, strategy, skipAutoRepair),
  }));
}

const { writeInstruction: appendInstruction } = require('./docs/syncFolder');
const { updateGitignore } = require('./gitignore/updateGitignore');

// Scan for skills missing from any registered tool target.
function scanUnwired(cwd, config, registry) {
  const skillsDir = path.join(cwd, '.easyskillz', 'skills');
  if (!fs.existsSync(skillsDir)) return [];
  const skills = fs.readdirSync(skillsDir).filter((n) =>
    fs.statSync(path.join(skillsDir, n)).isDirectory()
  );
  const missing = [];

  for (const skill of skills) {
    for (const toolId of config.tools) {
      const entry = registry[toolId.toLowerCase()];
      if (!entry) continue;

      const srcPath = path.resolve(cwd, '.easyskillz', 'skills', skill);
      const hasMissingTarget = getSkillTargets(entry, skill, srcPath)
        .some((target) => !isTargetWired(cwd, target, srcPath, config.linkStrategy));
      if (hasMissingTarget) missing.push({ skill, toolId, entry });
    }
  }
  return missing;
}

module.exports = {
  probeSymlinks,
  wireSkill,
  wireSkillToAllLocations,
  wireAllSkills,
  scanUnwired,
  isWired,
  isTargetWired,
  getSkillTargets,
  parseSkillFile,
  ensureValidSkill,
  appendInstruction,
  updateGitignore,
  GENERATED_MARKER,
};
